// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPackage(arg1) {
  return window['go']['application']['Driver']['AddPackage'](arg1);
}

export function AddProjectPackage(arg1) {
  return window['go']['application']['Driver']['AddProjectPackage'](arg1);
}

export function AggregateMetrics(arg1) {
  return window['go']['application']['Driver']['AggregateMetrics'](arg1);
}

export function CancelOperation(arg1) {
  return window['go']['application']['Driver']['CancelOperation'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['application']['Driver']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['application']['Driver']['DeleteProject'](arg1);
}

export function GetDetails() {
  return window['go']['application']['Driver']['GetDetails']();
}

export function GetOperation(arg1) {
  return window['go']['application']['Driver']['GetOperation'](arg1);
}

export function GetPackage(arg1) {
  return window['go']['application']['Driver']['GetPackage'](arg1);
}

export function GetPreferences() {
  return window['go']['application']['Driver']['GetPreferences']();
}

export function GetProject(arg1) {
  return window['go']['application']['Driver']['GetProject'](arg1);
}

export function InstallPackage(arg1) {
  return window['go']['application']['Driver']['InstallPackage'](arg1);
}

export function ListMetrics(arg1) {
  return window['go']['application']['Driver']['ListMetrics'](arg1);
}

export function ListOperations() {
  return window['go']['application']['Driver']['ListOperations']();
}

export function ListPackages(arg1) {
  return window['go']['application']['Driver']['ListPackages'](arg1);
}

export function ListProjects(arg1) {
  return window['go']['application']['Driver']['ListProjects'](arg1);
}

export function LongRunningOperation() {
  return window['go']['application']['Driver']['LongRunningOperation']();
}

export function LongRunningRequestWithCancellation(arg1) {
  return window['go']['application']['Driver']['LongRunningRequestWithCancellation'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['application']['Driver']['OpenDirectoryDialog'](arg1);
}

export function OpenExplorer(arg1) {
  return window['go']['application']['Driver']['OpenExplorer'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['application']['Driver']['OpenFileDialog'](arg1);
}

export function Quit() {
  return window['go']['application']['Driver']['Quit']();
}

export function RefreshPackages() {
  return window['go']['application']['Driver']['RefreshPackages']();
}

export function RemoveProjectPackage(arg1) {
  return window['go']['application']['Driver']['RemoveProjectPackage'](arg1);
}

export function RenderProject(arg1) {
  return window['go']['application']['Driver']['RenderProject'](arg1);
}

export function RunProject(arg1) {
  return window['go']['application']['Driver']['RunProject'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['application']['Driver']['SaveFileDialog'](arg1);
}

export function UninstallPackage(arg1) {
  return window['go']['application']['Driver']['UninstallPackage'](arg1);
}

export function UpdatePreferences(arg1) {
  return window['go']['application']['Driver']['UpdatePreferences'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['application']['Driver']['UpdateProject'](arg1);
}
