// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {uuid} from '../models';

export function AddPackage(arg1:application.AddPackageOpts):Promise<void>;

export function AddProjectPackage(arg1:application.AddProjectPackageOpts):Promise<void>;

export function AggregateMetrics(arg1:application.AggregateMetricsOpts):Promise<application.AggregateMetricsResult>;

export function CancelOperation(arg1:application.CancelOperationOpts):Promise<void>;

export function CreateProject(arg1:application.CreateProjectOpts):Promise<application.CreateProjectResult>;

export function DeleteProject(arg1:application.DeleteProjectOpts):Promise<void>;

export function GetDetails():Promise<application.Details>;

export function GetOperation(arg1:application.GetOperationOpts):Promise<application.GetOperationResult>;

export function GetPackage(arg1:application.GetPackageOpts):Promise<application.GetPackageResult>;

export function GetPreferences():Promise<application.Preferences>;

export function GetProject(arg1:application.GetPackageOpts):Promise<application.GetProjectResult>;

export function InstallPackage(arg1:application.InstallPackageOpts):Promise<application.InstallPackageResult>;

export function ListMetrics(arg1:application.ListMetricsOpts):Promise<application.ListMetricsResult>;

export function ListOperations():Promise<application.ListOperationsResult>;

export function ListPackages(arg1:application.ListPackagesOpts):Promise<application.ListPackagesResult>;

export function ListProjects(arg1:application.ListProjectsOpts):Promise<application.ListProjectsResult>;

export function LongRunningOperation():Promise<uuid.UUID>;

export function LongRunningRequestWithCancellation(arg1:uuid.UUID):Promise<void>;

export function OpenDirectoryDialog(arg1:application.OpenDialogOptions):Promise<string>;

export function OpenExplorer(arg1:application.OpenExplorerOptions):Promise<void>;

export function OpenFileDialog(arg1:application.OpenDialogOptions):Promise<string>;

export function Quit():Promise<void>;

export function RefreshPackages():Promise<void>;

export function RemoveProjectPackage(arg1:application.RemoveProjectPackageOpts):Promise<void>;

export function RenderProject(arg1:application.RenderProjectOpts):Promise<void>;

export function RunProject(arg1:application.RunProjectOpts):Promise<void>;

export function UninstallPackage(arg1:application.UninstallPackageOpts):Promise<void>;

export function UpdatePreferences(arg1:application.UpdatePreferencesOpts):Promise<void>;

export function UpdateProject(arg1:application.UpdateProjectOpts):Promise<void>;
