// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPackage(arg1) {
  return window['go']['application']['Driver']['AddPackage'](arg1);
}

export function CancelOperation(arg1) {
  return window['go']['application']['Driver']['CancelOperation'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['application']['Driver']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['application']['Driver']['DeleteProject'](arg1);
}

export function ExploreProject(arg1) {
  return window['go']['application']['Driver']['ExploreProject'](arg1);
}

export function GetApplicationConfig() {
  return window['go']['application']['Driver']['GetApplicationConfig']();
}

export function GetPackage(arg1) {
  return window['go']['application']['Driver']['GetPackage'](arg1);
}

export function GetPlatform() {
  return window['go']['application']['Driver']['GetPlatform']();
}

export function GetProject(arg1) {
  return window['go']['application']['Driver']['GetProject'](arg1);
}

export function GetRocketBlendConfig() {
  return window['go']['application']['Driver']['GetRocketBlendConfig']();
}

export function InstallPackage(arg1) {
  return window['go']['application']['Driver']['InstallPackage'](arg1);
}

export function ListPackages(arg1, arg2, arg3) {
  return window['go']['application']['Driver']['ListPackages'](arg1, arg2, arg3);
}

export function ListProjects(arg1) {
  return window['go']['application']['Driver']['ListProjects'](arg1);
}

export function LongRunningOperation() {
  return window['go']['application']['Driver']['LongRunningOperation']();
}

export function Quit() {
  return window['go']['application']['Driver']['Quit']();
}

export function RefreshPackages() {
  return window['go']['application']['Driver']['RefreshPackages']();
}

export function RenderProject(arg1) {
  return window['go']['application']['Driver']['RenderProject'](arg1);
}

export function RunProject(arg1) {
  return window['go']['application']['Driver']['RunProject'](arg1);
}

export function UninstallPackage(arg1) {
  return window['go']['application']['Driver']['UninstallPackage'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['application']['Driver']['UpdateProject'](arg1);
}
