name: Build Darwin

on:
  workflow_call:
    inputs:
      BUILD_TYPE:
        type: string
        description: "Build type: debug or release"
        required: true
      GO_VERSION:
        type: string
        description: "Full Go version to use, e.g. 1.21.1"
        required: true
      NODE_VERSION:
        type: string
        description: "Node version to use, e.g. 18, 20 etc"
        required: true
      WAILS_VERSION:
        type: string
        description: "Wails version to use, e.g. v2.7.0"
        required: true
      NOTARIZE:
        type: boolean
        description: "Whether to notarize the application"
        default: false
    outputs:
      ReleaseTag:
        value: ${{ jobs.Build.outputs.releaseTag }}

jobs:
  build-darwin:
    runs-on: macos-latest
    timeout-minutes: 30 # Notizing can sometimes take a long time:/
    permissions:
      contents: read
      packages: write
    outputs:
      releaseTag: ${{ steps.calculateReleaseTag.outputs.releaseTag }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_VERSION }}

      - name: Install Wails
        env:
          WAILS_VERSION: ${{ inputs.WAILS_VERSION }}
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@$WAILS_VERSION
          go install mvdan.cc/garble@latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Install Dependencies
        run: |
          brew install create-dmg

      - name: Generate Build Timestamp ISO 8601
        id: generateBuildTimestamp
        run: |
          BUILD_TIMESTAMP=$(date +'%Y-%m-%dT%H:%M:%S') && echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Calculate Release Tag
        id: calculateReleaseTag
        run: |
          RELEASE_TAG=$(git describe --tags 2>/dev/null || echo "v0.0.0")
          echo "Found release tag: $RELEASE_TAG"
          echo "releaseTag=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-node_modules-${{ hashFiles('./frontend/package-lock.json') }}
          path: "./frontend/node_modules"

      - name: Import Code Signing Certificates
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.AC_CERTIFICATE }}
          p12-password: ${{ secrets.AC_CERTIFICATE_PASSWORD }}

      - name: Build Application
        env:
          RELEASE_TAG: ${{ steps.calculateReleaseTag.outputs.releaseTag }}
          BUILD_TYPE: ${{ inputs.BUILD_TYPE }}
          BUILD_TIMESTAMP: ${{ steps.generateBuildTimestamp.outputs.BUILD_TIMESTAMP }}
          BUILD_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          COMMIT_SHA: ${{ github.sha }}
          NOTARIZE: ${{ inputs.NOTARIZE }}
          AC_CERTIFICATE: ${{ secrets.AC_CERTIFICATE }}
          AC_CERTIFICATE_PASSWORD: ${{ secrets.AC_CERTIFICATE_PASSWORD }}
          AC_APPLE_ID: ${{ secrets.AC_APPLE_ID }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          AC_TEAM_ID: ${{ secrets.AC_TEAM_ID }}
          AC_DEVELOPER_ID: ${{ secrets.AC_DEVELOPER_ID }}
          CGO_ENABLED: 1
        run: |
          go run mage.go prepare $RELEASE_TAG $BUILD_TIMESTAMP $COMMIT_SHA $BUILD_LINK $BUILD_TYPE $NOTARIZE

      - name: Run Go Tests
        run: |
          go test -v ./...

      - name: Upload Build Arifacts
        uses: actions/upload-artifact@v4
        with:
          name: release_bins_darwin
          path: ./build/bin/*
          if-no-files-found: error
          retention-days: 1