name: Build Cross Platform

on:
  workflow_call:
    inputs:
      BASE_IMAGE:
        type: string
        description: "Base image for cross compiling Wails applications with CGO"
        required: true
      BUILD_TYPE:
        type: string
        description: "Build type: release or debug"
        required: true
    outputs:
      ReleaseTag:
        value: ${{ jobs.Build.outputs.releaseTag }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: read
      packages: write
    outputs:
      releaseTag: ${{ steps.calculateReleaseTag.outputs.releaseTag }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Generate Build Timestamp ISO 8601
        id: generateBuildTimestamp
        run: |
          BUILD_TIMESTAMP=$(date +'%Y-%m-%dT%H:%M:%S') && echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Calculate Release Tag
        id: calculateReleaseTag
        run: |
          RELEASE_TAG=$(git describe --tags 2>/dev/null || echo "v0.0.0")
          echo "Found release tag: $RELEASE_TAG"
          echo "releaseTag=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Wails Application
        uses: docker/build-push-action@v6
        env:
          RELEASE_TAG: ${{ steps.calculateReleaseTag.outputs.releaseTag }}
        with:
          context: .
          push: false
          tags: |
            rocketblend_desktop_builder
          load: true
          cache-from: |
            type=registry,ref=ghcr.io/rocketblend/rocketblend-desktop/cache
          cache-to: type=registry,ref=ghcr.io/rocketblend/rocketblend-desktop/cache,mode=max
          build-args: |
            BASE_IMAGE=${{ inputs.BASE_IMAGE }}
            BUILD_TYPE=${{ inputs.BUILD_TYPE }}
            RELEASE_TAG=${{ env.RELEASE_TAG }}
            BUILD_TIMESTAMP=${{ steps.generateBuildTimestamp.outputs.BUILD_TIMESTAMP }}
            COMMIT_SHA=${{ github.sha }}
            BUILD_LINK=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Extract Build Artifacts
        run: |
          docker run --rm -v $(pwd)/build/bin:/artifacts rocketblend_desktop_builder

      - name: Upload Build Arifacts
        uses: actions/upload-artifact@v4
        with:
          name: release_bins
          path: ./build/bin/*
          if-no-files-found: error
          retention-days: 1