name: Build

on:
  workflow_call:
    inputs:
      base_image:
        type: string
        description: 'Base Docker image for cross-platform builds'
        default: 'ghcr.io/rocketblend/cross-wails:v2.8.0'
        required: false
      go_version:
        type: string
        description: 'Go version for Darwin builds'
        default: 'v1.22.1'
        required: false
      node_version:
        type: string
        description: 'Node version for Darwin builds'
        default: '20'
        required: false
      wails_version:
        type: string
        description: 'Wails version for Darwin builds'
        default: 'v2.8.0'
        required: false
      build_type:
        type: string
        description: 'Build type (e.g., release or debug)'
        default: 'release'
        required: false
      notarize:
        type: boolean
        description: "Whether to notarize the MacOS application (Darwin builds only)"
        default: false

jobs:
  build-windows-linux:
    uses: ./.github/workflows/build-windows-linux.yaml
    secrets: inherit
    with:
      BASE_IMAGE: ${{ inputs.base_image }}
      BUILD_TYPE: ${{ inputs.build_type }}

  build-darwin:
    uses: ./.github/workflows/build-darwin.yaml
    secrets: inherit
    with:
      GO_VERSION: ${{ inputs.go_version }}
      NODE_VERSION: ${{ inputs.node_version }}
      WAILS_VERSION: ${{ inputs.wails_version }}
      BUILD_TYPE: ${{ inputs.build_type }}
      NOTARIZE: ${{ inputs.notarize }}
