name: CD

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
      skip_publish:
        type: boolean
        description: "Skip publishing the release (if true)"
        required: false
        default: false
        # cosign_windows:
        #   type: boolean
        #   description: "Run Windows codesigning"
        #   required: false
        #   default: false

concurrency:
  group: rocketblend-desktop-cd
  cancel-in-progress: true

# Windows: Builds will eventually be signed via Azure Trusted Signing.
#          Currently unavailable for individuals; requires a registered LLC.
# macOS:   Codesigning and notarizing are handled in the CI step.
#          Consider splitting this into a dedicated step in the future.
# Linux:   Codesigning is not supported at this time.

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write 
    with:
      notarize: true

  # cosign-windows:
  #   if: ${{ github.event.inputs.cosign_windows == 'true' }}
  #   uses: ./.github/workflows/cosign-windows.yaml
  #   needs: build-cross-platform
  #   secrets: inherit
  #   with:
  #     artifact-name: release_bins_windows_linux
  #     artifact-path: bins
  #     endpoint: 'https://uksouth.codesigning.azure.net/'
  #     trusted-signing-account-name: ${{ secrets.TRUSTED_SIGNING_ACCOUNT_NAME }}
  #     certificate-profile-name: ${{ secrets.CERTIFICATE_PROFILE_NAME }}
  #     files-folder: bins
  #     files-folder-filter: 'exe,dll'
  #     description: 'RocketBlend Desktop'
  #     timestamp-rfc3161: 'http://timestamp.acs.microsoft.com'

  prepare-release-notes:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Generate Release Notes
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

  publish:
    if: ${{ github.event.inputs.skip_publish != 'true' }}
    runs-on: ubuntu-latest
    needs:
      - prepare-release-notes
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Darwin Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release_bins_darwin
          path: bins/darwin
      - name: Download Windows/Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release_bins_windows_linux
          path: bins/windows_linux
      # - name: Download Signed Windows Artifacts
      #   if: ${{ github.event.inputs.cosign_windows == 'true' }}
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: release_bins_signed
      #     path: bins_signed
      # - name: Replace Unsigned Windows Executables with Signed Versions
      #   if: ${{ github.event.inputs.cosign_windows == 'true' }}
      #   run: |
      #     cp -r bins_signed/* bins/windows_linux/
      - name: Upload Release Artifacts and Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bins/**/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ needs.prepare-release-notes.steps.changelog.outputs.changes }}
          draft: true
          generate_release_notes: false
