name: CD

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
        cosign_windows:
          description: "Run Windows codesigning"
          required: false
          default: "false"

concurrency:
  group: rocketblend-desktop-cd
  cancel-in-progress: true

# Windows: Builds will eventually be signed via Azure Trusted Signing.
#          Currently unavailable for individuals; requires a registered LLC.
# macOS:   Codesigning and notarizing are handled in the CI step.
#          Consider splitting this into a dedicated step in the future.
# Linux:   Codesigning is not supported at this time.

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      packages: write 

  cosign-windows:
    if: ${{ github.event.inputs.cosign_windows == 'true' }}
    uses: ./.github/workflows/cosign-windows.yaml
    needs: build-cross-platform
    with:
      artifact-name: release_bins
      artifact-path: bins
      endpoint: 'https://uksouth.codesigning.azure.net/'
      trusted-signing-account-name: ${{ secrets.TRUSTED_SIGNING_ACCOUNT_NAME }}
      certificate-profile-name: ${{ secrets.CERTIFICATE_PROFILE_NAME }}
      files-folder: bins
      files-folder-filter: 'exe,dll'
      description: 'RocketBlend Desktop'
      timestamp-rfc3161: 'http://timestamp.acs.microsoft.com'
    secrets:
      azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
      azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

  prepare-release-notes:
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Generate Release Notes
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}

  publish:
    runs-on: ubuntu-latest
    needs:
      - prepare-release-notes
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Unsigned Artifacts
        uses: actions/download-artifact@v3
        with:
          name: release_bins
          path: bins
      - name: Download Signed Windows Artifacts
        if: ${{ github.event.inputs.cosign_windows == 'true' }}
        uses: actions/download-artifact@v3
        with:
          name: release_bins_signed
          path: bins_signed
      - name: Replace Unsigned Windows Executables with Signed Versions
        if: ${{ github.event.inputs.cosign_windows == 'true' }}
        run: |
          cp -r bins_signed/* bins/
      - name: Upload Release Artifacts and Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bins/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ needs.prepare-release-notes.steps.changelog.outputs.changes }}
          draft: true
          generate_release_notes: false