name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      notarize:
        type: boolean
        description: "Enable notarization"
        required: false
        default: false

concurrency:
  group: rocketblend-desktop-ci
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      notarize: ${{ github.event.inputs.notarize != 'false' }}
  
  # Testings
  download:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download Darwin Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release_bins_darwin
          path: bins/darwin
      - name: Download Windows/Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release_bins_windows_linux
          path: bins/windows_linux
