name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: rocketblend-desktop-ci
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write 
