name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: rocketblend-desktop-ci
  cancel-in-progress: true

jobs:
  build-cross-platform:
    uses: ./.github/workflows/builds/cross-platform.yaml

    permissions:
      contents: read
      packages: write

    with:
      BASE_IMAGE: ghcr.io/abjrcode/cross-wails:v2.7.1
      BUILD_TYPE: "release"

  build-darwin:
    uses: ./.github/workflows/builds/darwin.yaml

    with:
      GO_VERSION: "v1.21.5"
      NODE_VERSION: "20"
      WAILS_VERSION: "v2.7.1"
      BUILD_TYPE: "release"