name: PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - master
  workflow_dispatch:

permissions:
  pull-requests: write

concurrency:
  group: rocketblend-desktop-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr-title:
    uses: rocketblend/github-workflows/.github/workflows/validate-pr-title.yaml@main
    permissions:
      pull-requests: write

  build:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/build.yaml
    with:
      build_type: "debug"